Controllers/AccountsController.cs
using LojinhaDaPaulinha.Data.Identity;
using LojinhaDaPaulinha.Models.Account;
using Microsoft.AspNetCore.Mvc;

namespace LojinhaDaPaulinha.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IIdentityManager _identityManager;

        private bool IsUserAuthenticated => User?.Identity?.IsAuthenticated ?? false;

        public AccountsController(IIdentityManager identityManager)
        {
            _identityManager = identityManager;
        }


        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Login()
        {
            if (IsUserAuthenticated) return Redirect("/Home");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return LoginModelStateInvalid(model);
            }

            // Try login.
            var signIn = await _identityManager.SignInAsync(model.UserName, model.Password, model.RememberMe);

            // If Login succeeded.
            if (signIn.Succeeded)
            {
                // Redirect to ReturnUrl or /Home.
                return Redirect((string)Request.Query["ReturnUrl"] ?? "/Home");
            }
            // If Login did not succeed.
            else
            {
                // Check user exists.
                if (!await _identityManager.UserExistsAsync(model.UserName))
                {
                    ModelState.AddModelError(string.Empty, "This user is not registered.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Could not login.");
                }

                return View(model);
            }
        }

        public async Task<IActionResult> Logout()
        {
            if (IsUserAuthenticated)
                await _identityManager.SignOutAsync();

            return Redirect("/Home");
        }

        #region private helper methods

        private IActionResult LoginModelStateInvalid(LoginViewModel model)
        {
            ModelState.AddModelError(
                string.Empty,
                "Could not login - input was not accepted. Make sure you give a Username and a Password.");

            return View(model);
        }

        #endregion private helper methods
    }
}

Controllers/ProductsController.cs
using LojinhaDaPaulinha.Models.Entities.Product;
using LojinhaDaPaulinha.Services.Api;
using LojinhaDaPaulinha.Services.Data;
using LojinhaDaPaulinha.Utils;
using Microsoft.AspNetCore.Mvc;

namespace LojinhaDaPaulinha.Controllers
{
    public class ProductsController : AppController
    {
        private readonly DataService _dataService;

        protected override async Task GetInputCombos()
        {
            // This entity doesn't need Input Combos.
            await Task.CompletedTask;
        }

        public ProductsController(DataService dataService)
        {
            _dataService = dataService;
        }


        // GET: Products
        public async Task<IActionResult> Index()
        {
            try 
            {
                var getAll = await _dataService.GetAsync<IEnumerable<IndexRowProductViewModel>>(ApiUrls.GetAllProducts);
                return ManageGetDataResponse<IEnumerable<IndexRowProductViewModel>>(getAll);
            }
            catch (HttpRequestException ex)
            {
                return View("Error");
            }
        }


        // GET: Products/5
        public async Task<IActionResult> Details(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.Product);

            // Try get model.
            var getModel = await _dataService.GetAsync<DisplayProductViewModel>(ApiUrls.GetProductDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductViewModel>(getModel);
        }


        // GET: Products/Create
        public async Task<IActionResult> Create()
        {
            return await ViewInput(null);
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductViewModel model)
        {
            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.Product);

            // Try create Product.
            var create = await _dataService.CreateAsync(ApiUrls.CreateProduct, model);

            // Resolve response.
            return ManageInputResponse(create);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.Product);

            // Try to get model.
            var getModel = await _dataService.GetAsync<EditProductViewModel>(ApiUrls.GetProductEditModel, id);

            // Resolve response.
            return ManageGetDataResponse<EditProductViewModel>(getModel);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductViewModel model)
        {
            // Check given ID is valid.
            if (model.Id < 1) return IdIsNotValid(EntityNames.Product);

            if (!ModelState.IsValid)
                return await ModelStateInvalid(model, EntityNames.Product);

            // Try update Product.
            var update = await _dataService.UpdateAsync(ApiUrls.UpdateProduct, model);

            // Resolve response.
            return ManageInputResponse(update);
        }


        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id < 1) return IdIsNotValid(EntityNames.Product);

            // Try get Model.
            var getModel = await _dataService.GetAsync<DisplayProductViewModel>(ApiUrls.GetProductDisplay, id);

            // Resolve response.
            return ManageGetDataResponse<DisplayProductViewModel>(getModel);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            // Check given ID is valid.
            if (id < 1) return IdIsNotValid(EntityNames.Product);

            // Try delete Product.
            var delete = await _dataService.DeleteAsync(ApiUrls.DeleteProduct, id);

            // Resolve response.
            return ManageDeleteResponse(delete);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lojinha Da Paulinha</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Scripts", required: false)
</head>

@{
    var userIdentity = User?.Identity;
    bool _isUserAuthenticated = userIdentity?.IsAuthenticated ?? false;
    bool _isUserInRoleAdmin = User?.IsInRole("Admin") ?? false;
    bool _isUserInRoleTechnician = User?.IsInRole("Technician") ?? false;
    string _userName = userIdentity?.Name ?? "error: username not found";
}
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand asp-controller=" Home" asp-action="Index">Lojinha Da Paulinha</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Categories">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Contact">Contact</a>
                        </li>
                    </ul>
                    @if (_isUserAuthenticated)
                    {

                        <ul class="navbar-nav flex-grow-1">
                        </ul>
                        <ul class="navbar-nav right">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">@_userName</a>
                                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-controller="Accounts" asp-action="Logout">Logout</a></li>
                                    </ul>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                        </ul>
                        <ul class="navbar-nav navbar-right">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Accounts" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    }

                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container mt-4">
        @RenderBody()
    </main>
    <footer class="footer mt-auto py-3 bg-dark text-white">
        <div class="container text-center">
            <span class="text-muted">© 2024 Lojinha Da Paulinha</span>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js"></script>
</body>
</html>

Views/Shared/_LayoutMessage.cshtml
@if (TempData["LayoutMessageError"] != null)
{
    <p class="mx-5 px-3 text-danger">@TempData["LayoutMessageError"]</p>
}

@if (TempData["LayoutMessageWarning"] != null)
{
    <p class="mx-5 px-3 text-warning">@TempData["LayoutMessageWarning"]</p>
}

@if (TempData["LayoutMessageSuccess"] != null)
{
    <h6 class="mx-5 px-3 text-success">@TempData["LayoutMessageSuccess"]</h6>
}

@if (TempData["LayoutMessage"] != null)
{
    <p class="mx-5 px-3">@TempData["LayoutMessage"]</p>
}